##################################################################################
# Cloudify Fabric built in types and plugins definitions.
##################################################################################
plugins:
    fabric:
        executor: central_deployment_agent
        source: https://github.com/denismakogon/cloudify-fabric-plugin/archive/CFY-3294.zip